global_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   update_frequency: 1.0
   publish_frequency: 0
   static_map: false
   rolling_window: false
   resolution: 0.1
   transform_tolerance: 0.2
   width: 100.0
   height: 100.0
   map_type: costmap
   plugins:
      - {name: static_map,       type: "costmap_2d::StaticLayer"}
      - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
      - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
